version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080

  ollama:
    image: ollama/ollama
    # command: ["ollama", "run", "phi"]
    ports:
      - 11434:11434
    volumes:
      - ollama-vol:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama-vol:
