version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fallback.html:/usr/share/nginx/html/fallback.html;
    networks:
      - all-in-one

  proxy:
    build: .
    environment:
      - SERVER_NAME=localhost
    networks:
      - all-in-one

networks:
  all-in-one:
    external: true
